base_url = "https://blog.yanlincs.com"
title = "Yan Lin's Blog"
description = "Personal blog of Yan Lin, Postdoctoral Researcher at Aalborg University"
default_language = "en"
compile_sass = true
minify_html = false
generate_feeds = true
feed_filenames = ["rss.xml"]
ignored_content = ["*.svg", "*.drawio", "*.png", "*.jpg", "*.jpeg"]

[markdown]
highlighting = { light_theme = "github-light", dark_theme = "github-dark" }
external_links_target_blank = true

[extra]
author = "Yan Lin"
