base_url = "https://blog.yanlincs.com"
title = "Yan Lin's Blog"
description = "Personal blog of Yan Lin, Postdoctoral Researcher at Aalborg University"
default_language = "en"
compile_sass = true
minify_html = false
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
author = "Yan Lin"
